[package]
name = "hcomp"
version = "0.1.0"
edition = "2021"

[dependencies]
libwebp-sys = { version = "0.9.4", features = ["avx2", "neon", "sse41"] }

[workspace]
members = [
    ".",
    "compare",
]
