[package]
name = "compare"
version = "0.1.0"
edition = "2021"

[dependencies]
libwebp-sys = { version = "0.9.4", features = ["avx2", "neon", "sse41"] }
png = "0.17.5"
tiff = { git = "https://github.com/image-rs/image-tiff" }
zstd = "0.11.2"

hcomp = { path = ".." }
